### ISSUE TITLE
Clarifying that the current version requires mpich and not working with openmpi

### ISSUE THREAD

**Issue by sandrain** [LLNL/UnifyCR#115]
The current version of UnifyCR adopts the mdhim key-value store, which strictly requires 

> An MPI distribution that supports MPI_THREAD_MULTIPLE and per-object locking of critical sections  (this excludes OpenMPI)

as specified in the project [github](https://github.com/mdhim/mdhim-tng).

Until we put an alternative metadata store, this should be explained in the documentation, such as the 'How to build UnifyCR' page.

**Comment by dsikich** [comment]
@sandrain yes, that is a good point. We should add a note about that on the build page.

**Comment by dsikich** [comment]
#116

**Comment by sandrain** [comment]
This has been properly address by #116 thus will be closed.
