### ISSUE TITLE
Static client initialization and finalization

### ISSUE THREAD

**Issue by MichaelBrim** [LLNL/UnifyCR#134]
### Description
In order to make the use of UnifyCR more seamless, it is desirable to eliminate the need for client applications to directly call `unifycr_mount()` and `unifycr_unmount()`. Thus, we would like to call these functions as part of the client library's static initialization and finalization. This issue is to document the roadblocks to doing such static setup/teardown.

### Initialization roadblocks

- MPI is used extensively during `unifycr_mount()`, but an application will not call `MPI_Init()` until after the library is initialized. Similarly, the MPI rank space is used as the UnifyCR global rank space, and the local rank and size of `MPI_COMM_WORLD` are passed as arguments to `unifycr_mount()`.

### Finalization roadblocks

- No problems identified yet.

**Comment by MichaelBrim** [comment]
In PR #288, Adam is working on using PMPI wrappers for MPI_Init and MPI_Finalize to call mount and unmount.

**Comment by MichaelBrim** [comment]
PR #298 added the PMPI wrapper method for mount/unmount

**Comment by adammoody** [comment]
Thanks @MichaelBrim
