### ISSUE TITLE
First 24 bytes of read transfer are corrupt

### ISSUE THREAD

**Issue by jgmoore-or** [LLNL/UnifyCR#139]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | RHEL
OS Version             |     7.4
Architecture           |     X86-64
UnifyCR Version        |   multiple

### Describe the problem you're observing

First 24 bytes of read transfer are corrupt

### Describe how to reproduce the problem

1. Instrumented "test_write" program to set contents of 4k transfer writes to contain incremented byte values: 0,1,2,... (i.e., all zeros in the first write, all 1s in the second write, etc.)
2. Completed 128 transfers in the test program
3. Instrumented test_read to to verify content of reads; found that the first 24 bytes of each transfer did not contain the values written. Instead these 24 bytes were constant for all transfers, except for the byte at offset 9 (zero relative), which changes with each transfer.

### Additional testing

Put in tracing to verify that the metadata updates for the writes and metadata lookups for the reads are both correct.

**Comment by jgmoore-or** [comment]
This defect is caused by a bug in function rm_process_received_msg in the unifycr_request_manager.c.  The bug is on line 517 of the current version of this file in the dev branch.

The statement:

 memcpy(2 * sizeof(int)
               + app_config->shm_recv_bufs[client_id] + *ptr_size,
               (void *)tmp_recv_msg,
               tmp_recv_msg->length + sizeof(recv_msg_t));

is copying from the wrong address.  When this is change to use the address 24 bytes further into the buffer passed to the rm_process_received_msg function, the read transfer to the client completes successfully.

**Comment by adammoody** [comment]
Nice debugging, @jgmoore-or!

**Comment by jgmoore-or** [comment]
Also, the last parameter for memcpy (the size of the transfer) is incorrect.   The size should be the value in tmp_recv_msg->length.  The struct members (src_fid, offset, length) are directly assigned, the memcpy should only transfer the data buffer that follows (of length tmp_recv_msg->length).

**Comment by jgmoore-or** [comment]
An incorrect fix for this was pulled in issue #94.  This change was altered (still incorrect) in issue #99 and then reverted back by the author of #94. The change introduced in #94  (and recovered in the was to add the length of the recv_msg_t struct to the length to copy. However, this is incorrect. The length to copy should be tmp_recv_msg->length. The adjustment should instead be made to the source address. The address of the start of the read data buffer is the offset just beyond the recv_msg_t struct (temp_recv_msg):

  memcpy(2 * sizeof(int)
               + app_config->shm_recv_bufs[client_id] + *ptr_size,
               (void*)(tmp_recv_msg + 1),
               tmp_recv_msg->length);

Note that the "+ 1" increments the address by sizeof(recv_msg_t): 24 bytes. I would also like to comment that the use of pointer arithmetic to calculate offsets into memory buffers is error-prone. The change to Mercury-based communication will eliminate the use of raw buffers for communication  and thus eliminate the need for this style of coding.

**Comment by dsikich** [comment]
@jgmoore-or I agree, these errors will be much easier to spot once we move away from doing pointer arithmetic to calculate the offsets into memory buffers. And the code will be easier to read.

**Comment by sandrain** [comment]
This unfortunately does not fix the hdf5 related problems. I will further debug what exactly fails with hdf5.

**Comment by sandrain** [comment]
This specific bug has been fixed.
