### ISSUE TITLE
UNIFYCR_MAX_FILENAME vs. ULFS_MAX_FILENAME

### ISSUE THREAD

**Issue by boehms** [LLNL/UnifyCR#140]
There are two *_MAX_FILENAME definitions in the source. ULFS_MAX_FILENAME is defined to 256 and UNIFYCR_MAX_FILENAME is defined to 128.
It there a reason for the two definitions?

**Comment by MichaelBrim** [comment]
ULFS_MAX_FILENAME is no longer in use after my recent configuration updates. Check to make sure your code is up to date.
