### ISSUE TITLE
Clean up spill logs left on ssd

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyCR#157]
Came across a "permission denied" error when attempting to run app-mpiio-gotcha test. We tracked it down to the spill log being created on the ssd. There were leftover spill log files from other users on the compute node.
Since these files weren't cleaned up, UnifyCR attempted to use those left over files from other users instead of creating new ones.

Need to make sure we clean up leftover log files after each run to prevent these permission errors when multiple users end up running UnifyCR on the same compute node.

**Comment by CamStan** [comment]
This could be done automatically when the user runs `unifycr terminate` or when they include the `--cleanup, -c` option, which appears to not be implemented at the moment.

The `terminate` command
https://github.com/LLNL/UnifyCR/blob/def34a8e339a043332f8e8ff882fff65673585b9/util/unifycr/src/unifycr.c#L237-L238

calls `.cleanup` for the current resource manager and passes `-c` option through,

https://github.com/LLNL/UnifyCR/blob/def34a8e339a043332f8e8ff882fff65673585b9/util/unifycr/src/unifycr-rm.c#L733-L734

where the server is terminated successfully.

https://github.com/LLNL/UnifyCR/blob/def34a8e339a043332f8e8ff882fff65673585b9/util/unifycr/src/unifycr-rm.c#L590-L591

However, `args` is never used and the temporary data locally stored on each node (including the spill logs) still appear to remain after termination.

**Comment by MichaelBrim** [comment]
Yes, until PR #179, the terminate mode didn't do anything, so I added the cleanup methods with a rudimentary "just kill the servers" implementation. Support for `--cleanup` is still TO-DO. Currently, there is no way to communicate this option to the servers, and we should probably discuss this at the next telecon.

**Comment by MichaelBrim** [comment]
PR #190 adds `--cleanup` to `start` mode options, and associated server CLI arg.

**Comment by MichaelBrim** [comment]
I believe this issue is now resolved - I verified that on normal shutdown the cleanup is performed. However, there will still be cases where the server dies (e.g., segfaults) and leaves a mess of state around, but there's no easy solution for that. I think this failure behavior is what led to the initial bug report.
