### ISSUE TITLE
Need a travis cache refresh for the margo spack package

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyCR#200]
The m2 branch is currently failing in travis when installing margo.

```
0.37s$ git clone https://xgitlab.cels.anl.gov/sds/sds-repo.git $HOME/sds-repo.git
Cloning into '/home/travis/sds-repo.git'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 894 (delta 8), reused 0 (delta 0)
Receiving objects: 100% (894/894), 103.72 KiB | 1.79 MiB/s, done.
Resolving deltas: 100% (513/513), done.
before_install.12
0.29s$ $HOME/spack/bin/spack repo add $HOME/sds-repo.git
==> Added repo with namespace 'sds'.
0.94s$ $HOME/spack/bin/spack install margo
==> Error: Class constructor failed for package 'margo'.
Caused by:
NoURLError: Package Margo has no version with a URL.
  File "/home/travis/spack/lib/spack/spack/repo.py", line 833, in get
    return package_class(spec)
  File "/home/travis/spack/lib/spack/spack/package.py", line 625, in __init__
    f = fs.for_package_version(self, self.version)
  File "/home/travis/spack/lib/spack/spack/fetch_strategy.py", line 996, in for_package_version
    attrs['url'] = pkg.url_for_version(version)
  File "/home/travis/spack/lib/spack/spack/package.py", line 753, in url_for_version
    raise NoURLError(cls)
The command "$HOME/spack/bin/spack install margo" failed and exited with 1 during .
Your build has been stopped.
```

I had this working at one time, but the margo spack package has since been updated.  I was able to reproduce the build error message in my local build by spack uninstalling margo, pulling the latest margo spack package from Argonne, and then reinstalling margo using spack.

I found that if I refreshed spack itself, but pulling the latest develop branch, then margo was able to install again.  So I think the newer margo spack package must be using some newer spack feature that the spack in our travis cache does not support.

Anyone know how to reset our travis cache to force it to get a fresh spack?

https://docs.travis-ci.com/user/caching

Otherwise, perhaps it works to add a "cd spack && git pull".

**Comment by CamStan** [comment]
@adammoody, when you're logged into Travis, there should be a "More Options" hamburger menu at the top right on the build that is failing. Click that and there should be a "Caches" option. All the cached builds should show up there and you can click the trash can icon on the far right of the one you want to reset.

Hopefully that is what you're looking for.

**Comment by adammoody** [comment]
Thanks, @CamStan .  I looked for that earlier, but it didn't show up for me.  Since you confirmed that step in your comment, I took another look and found it this time.

That seems to have fixed the spack/margo version problem.  Failing due to something else now, but at least we're past this problem.  Thanks!
