### ISSUE TITLE
unifycr.h public header file is broken. It requires unifycr-internal.h.

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyCR#23]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       |
OS Version             |
Architecture           |
UnifyCR Version        |

**Comment by dsikich** [comment]
@adammoody I'm not sure what this means? I looked in unifycr.h, and it does not include unifycr-internal.h?

**Comment by nedbass** [comment]
I suspect this issue is about this error which you get if you include unifycr.h from an client program:

```
In file included from sys/open.c(23):
../client/src/unifycr.h(67): error: identifier "UNIFYCR_MAX_FILENAME" is undefined
      char hostname[UNIFYCR_MAX_FILENAME];
```

UNIFYCR_MAX_FILENAME is defined in unifycr-defs.h which seems to be a private header.

I think an appropriate fix would be to use an array size of HOST_NAME_MAX, which is defined in limits.h.
