### ISSUE TITLE
gotcha_map_unifycr_list.h:108:39: warning: initialization of ‘void **’ from incompatible pointer type

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyCR#340]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Fedora
OS Version             | 30
Architecture           | x86-64
UnifyCR Version        | dev

### Describe the problem you're observing
It seems UnifyCR will not build against the latest GOTCHA:
```
make[3]: Entering directory '/home/hutter/UnifyCR/client/src'
  CC       libunifycr_gotcha_la-unifycr.lo
In file included from unifycr.c:58:
gotcha_map_unifycr_list.h:108:39: warning: initialization of ‘void **’ from incompatible pointer type ‘int (**)(const char *, int)’ [-Wincompatible-pointer-types]
  108 |     { "access", UNIFYCR_WRAP(access), &UNIFYCR_REAL(access) },
```
Looks like they changed some of the interfaces (https://github.com/LLNL/GOTCHA/commit/5456986850ae5181e7daccf3aa168e2126a4b53c)

### Describe how to reproduce the problem
Build UnifyCR with latest GOTCHA.

**Comment by CamStan** [comment]
See #151

**Comment by tonyhutter** [comment]
Looks like a duplicate, closing issue.
