### ISSUE TITLE
 unifycr-stdio.c:694:9: warning: statement with no effect: s->ubuflen;

### ISSUE THREAD

**Issue by nedbass** [LLNL/UnifyCR#64]
https://github.com/LLNL/UnifyCR/blob/2cc38254e3bf25a07c2619bf5fdc577725568869/client/src/unifycr-stdio.c#L694

It seems `s->ubuflen` was meant to be updated here, but it's unclear to me what the correct assignment is.

**Comment by nedbass** [comment]
@violinteng do you know what the correct assignment for `s->ubuflen` is here? The corresponding line in burstfs is

https://github.com/LLNL/burstfs/blob/6bb101c16802e87241cda2b5ee3ceca3e28dfc04/BurstFS_Client/src/cruise-stdio.c#L757

Thanks!

**Comment by violinteng** [comment]
Hi Ned,

Sorry. I just realized your message. s->ubuflen is from CRUISE code. 
I think based on the context here (append), the value of s->ubuflen is 
probably 0. You may confirm with Adam or Kathryn as they are 
the authors for this piece of code.

**Comment by violinteng** [comment]
Hi Ned,

Sorry. I just realized your message. s->ubuflen is from CRUISE code. 
I think based on the context here (append), the value of s->ubuflen is 
probably 0. You may confirm with Adam or Kathryn as they are 
the authors for this piece of code.

**Comment by adammoody** [comment]
I updated this line to set ubuflen = 0.  While doing that, it occurred to me that FILE* stream code should be reviewed for other cases, e.g., fwrite() of 0 bytes seems to not change the file pointer or the push back buffer in libc, but our wrapper does both.

**Comment by MichaelBrim** [comment]
closing this issue, and opening a new one for stdio review
