### ISSUE TITLE
unifycr-stdio.c:2825:16: warning: ‘nr’ may be used uninitialized in __svfscanf

### ISSUE THREAD

**Issue by nedbass** [LLNL/UnifyCR#68]
The handling of `nr` in __svfscanf looks buggy and triggers this warning:

```
unifycr-stdio.c: In function ‘__svfscanf’:
unifycr-stdio.c:2825:16: warning: ‘nr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (nr < 0) {
                ^
```

https://github.com/LLNL/UnifyCR/blob/2cc38254e3bf25a07c2619bf5fdc577725568869/client/src/unifycr-stdio.c#L2828

**Comment by MichaelBrim** [comment]
I fixed this one in PR #132
