### ISSUE TITLE
This function name failed to be wrapped: stat

### ISSUE THREAD

**Issue by nedbass** [LLNL/UnifyCR#75]
I note this error when running `test_write_gotcha`:

```
$ srun -n 1 -N 1 ./test_write_gotcha -f foo -b 1024 -t 1024 -s 1024
rank:0, openning file /l/ssd/spill_0_0.log failure: No such file or directory
This function name failed to be wrapped: stat
Aggregate Write BW is 530.503979MB/s, Min Write BW is 530.503979MB/s
```

**Comment by dsikich** [comment]
@nedbass Stat was one of the functions that can potentially have multiple names. It is stat at the application level, but could really be calling like __xstat or __lxstat in reality. I believe in this case there is a macro in glibc header files that defines stat as __xstat. LD_PRELOAD will also suffer from this issue, but gotcha lets you know when that name failed to be wrapped successfully. 

We talked a while back about making sure that there was at least one function for that call wrapped successfully. So, if one of (__lxstat, __xstat, or stat) was successfully wrapped should we leave out this error? If we add this, then that feature would only be usable with gotcha (or you were checking at runtime which functions gotcha did successfully wrap?) I'm not sure. The other thing I am not sure about is if these names may depend on the version of glibc used? 

For now, maybe allowing which functions failed to be wrapped is confusing until we add that functionality?

**Comment by nedbass** [comment]
My feeling is that it's best practice for libraries to avoid printing anything to the console. Or at the very least only under exceptional or fatal conditions. A good design might be to provide a way for the unifycr library to success/failure information to the application in some way, so the application could decide how to handle it. A simpler approach might be to be silent by default, but provide a way to enable a debug or verbose mode that would print the messages. e.g. setting UNIFYCR_VERBOSE=n where increasing values of n provide more info.

**Comment by dsikich** [comment]
@nedbass Okay, thanks. I can add the simpler silent mode sometime today or tomorrow, and I think that will avoid the confusion until we add more.

**Comment by dsikich** [comment]
closing this since gotcha no longer prints these when debug is off
