### ISSUE TITLE
Make an annotated tag for v0.1.0

### ISSUE THREAD

**Issue by nedbass** [LLNL/UnifyCR#83]
@kathrynmohror I'd like to suggest that we make an annotated git tag for release 0.1.0, retroactively applied to commit 4c5be05 (the current tip of the master branch where the license was added). This will allow `git describe` to work correctly, which is useful for generating correctly versioned tarballs with `make dist`. To do this, you'd run

```
git tag -a -m "Tag version v0.1.0" v0.1.0 4c5be05
git push origin --tags v0.1.0
```

**Comment by kathrynmohror** [comment]
Great suggestion @nedbass! I executed the commands you supplied (thanks ;-))
